#include "gui_core.h"
 
 
extern int app_file_list_create(const char* widgetname, void *usrdata);
extern int app_file_list_destroy(const char* widgetname, void *usrdata);
extern int app_file_list_get_total(const char* widgetname, void *usrdata);
extern int app_file_list_keypress(const char* widgetname, void *usrdata);
extern int app_file_list_get_data(const char* widgetname, void *usrdata);
extern int app_file_list_draw(const char* widgetname, void *usrdata);
extern int app_file_list_change(const char* widgetname, void *usrdata);
extern int app_popmsg_init(const char* widgetname, void *usrdata);
extern int app_popmsg_keypress(const char* widgetname, void *usrdata);
extern int top(const char* widgetname, void *usrdata);
extern int app_update_menu_create(const char* widgetname, void *usrdata);
extern int app_update_menu_destroy(const char* widgetname, void *usrdata);
extern int app_update_menu_keypress(const char* widgetname, void *usrdata);
extern int app_update_menu_box_keypress(const char* widgetname, void *usrdata);
extern int app_update_manual_create(const char* widgetname, void *usrdata);
extern int app_update_manual_destroy(const char* widgetname, void *usrdata);
extern int app_update_manual_keypress(const char* widgetname, void *usrdata);
extern int app_update_manual_box_keypress(const char* widgetname, void *usrdata);
extern int app_update_manual_service(const char* widgetname, void *usrdata);
extern int app_advanced_menu_create(const char* widgetname, void *usrdata);
extern int app_advanced_menu_keypress(const char* widgetname, void *usrdata);
extern int app_advanced_menu_destroy(const char* widgetname, void *usrdata);
extern int app_advanced_menu_box_keypress(const char* widgetname, void *usrdata);
extern int win_all_search_create(const char* widgetname, void *usrdata);
extern int win_all_search_destroy(const char* widgetname, void *usrdata);
extern int win_all_search_keypress(const char* widgetname, void *usrdata);
extern int win_audio_set_service(const char* widgetname, void *usrdata);
extern int win_audio_set_create(const char* widgetname, void *usrdata);
extern int win_audio_set_destroy(const char* widgetname, void *usrdata);
extern int win_audio_set_keypress(const char* widgetname, void *usrdata);
extern int book_manage_service(const char* widgetname, void *usrdata);
extern int book_manage_create(const char* widgetname, void *usrdata);
extern int book_manage_destroy(const char* widgetname, void *usrdata);
extern int book_manage_keypress(const char* widgetname, void *usrdata);
extern int book_manage_listview_get_count(const char* widgetname, void *usrdata);
extern int book_manage_listview_get_data(const char* widgetname, void *usrdata);
extern int book_manage_listview_change(const char* widgetname, void *usrdata);
extern int book_manage_listview_draw(const char* widgetname, void *usrdata);
extern int book_manage_listview_keypress(const char* widgetname, void *usrdata);
extern int app_ca_info_menu_create(const char* widgetname, void *usrdata);
extern int app_ca_info_menu_keypress(const char* widgetname, void *usrdata);
extern int win_channel_set_create(const char* widgetname, void *usrdata);
extern int win_channel_set_destroy(const char* widgetname, void *usrdata);
extern int win_channel_set_keypress(const char* widgetname, void *usrdata);
extern int win_favorite_prog_list_create(const char* widgetname, void *usrdata);
extern int win_favorite_prog_list_destroy(const char* widgetname, void *usrdata);
extern int win_favorite_prog_list_keypress(const char* widgetname, void *usrdata);
extern int win_favorite_prog_listview_get_total(const char* widgetname, void *usrdata);
extern int win_favorite_prog_listview_get_data(const char* widgetname, void *usrdata);
extern int win_favorite_prog_listview_change(const char* widgetname, void *usrdata);
extern int win_favorite_prog_list_show(const char* widgetname, void *usrdata);
extern int app_full_screen_create(const char* widgetname, void *usrdata);
extern int full_screen_service(const char* widgetname, void *usrdata);
extern int app_full_screen_destroy(const char* widgetname, void *usrdata);
extern int app_full_screen_keypress(const char* widgetname, void *usrdata);
extern int win_lang_set_service(const char* widgetname, void *usrdata);
extern int win_lang_set_create(const char* widgetname, void *usrdata);
extern int win_lang_set_destroy(const char* widgetname, void *usrdata);
extern int win_lang_set_keypress(const char* widgetname, void *usrdata);
extern int win_main_frequency_set_create(const char* widgetname, void *usrdata);
extern int win_main_frequency_set_destroy(const char* widgetname, void *usrdata);
extern int win_main_frequency_set_keypress(const char* widgetname, void *usrdata);
extern int win_main_menu_create(const char* widgetname, void *usrdata);
extern int win_main_menu_destroy(const char* widgetname, void *usrdata);
extern int win_main_menu_keypress(const char* widgetname, void *usrdata);
extern int win_main_menu_show(const char* widgetname, void *usrdata);
extern int app_main_menu_boxr_keypress(const char* widgetname, void *usrdata);
extern int app_main_menu_box_keypress(const char* widgetname, void *usrdata);
extern int win_manual_search_create(const char* widgetname, void *usrdata);
extern int win_manual_search_destroy(const char* widgetname, void *usrdata);
extern int win_manual_search_keypress(const char* widgetname, void *usrdata);
extern int win_epg_list_create(const char* widgetname, void *usrdata);
extern int win_epg_list_lost_focus(const char* widgetname, void *usrdata);
extern int win_epg_list_destroy(const char* widgetname, void *usrdata);
extern int win_epg_list_show(const char* widgetname, void *usrdata);
extern int win_epg_list_keypress(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_get_total(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_get_data(const char* widgetname, void *usrdata);
extern int app_epg_prog_list_change(const char* widgetname, void *usrdata);
extern int app_epg_schedule_listview_change(const char* widgetname, void *usrdata);
extern int app_epg_schedule_listview_get_total(const char* widgetname, void *usrdata);
extern int app_epg_schedule_listview_get_data(const char* widgetname, void *usrdata);
extern int win_menu_tv_list_create(const char* widgetname, void *usrdata);
extern int win_menu_tv_list_destroy(const char* widgetname, void *usrdata);
extern int win_menu_tv_list_keypress(const char* widgetname, void *usrdata);
extern int win_tv_prog_listview_get_total(const char* widgetname, void *usrdata);
extern int win_tv_prog_listview_get_data(const char* widgetname, void *usrdata);
extern int win_tv_prog_listview_change(const char* widgetname, void *usrdata);
extern int win_passwd_set_service(const char* widgetname, void *usrdata);
extern int win_passwd_set_create(const char* widgetname, void *usrdata);
extern int win_passwd_set_destroy(const char* widgetname, void *usrdata);
extern int win_passwd_set_box_keypress(const char* widgetname, void *usrdata);
extern int win_passwd_set_keypress(const char* widgetname, void *usrdata);
extern int win_password_check_create(const char* widgetname, void *usrdata);
extern int win_password_check_destroy(const char* widgetname, void *usrdata);
extern int win_password_check_edit_keypress(const char* widgetname, void *usrdata);
extern int win_password_check_reach_end(const char* widgetname, void *usrdata);
extern int win_password_check_keypress(const char* widgetname, void *usrdata);
extern int win_password_input_create(const char* widgetname, void *usrdata);
extern int win_password_input_destroy(const char* widgetname, void *usrdata);
extern int win_password_input_edit_keypress(const char* widgetname, void *usrdata);
extern int win_password_input_reach_end(const char* widgetname, void *usrdata);
extern int win_password_input_keypress(const char* widgetname, void *usrdata);
extern int win_pop_tip_create(const char* widgetname, void *usrdata);
extern int win_pop_tip_destroy(const char* widgetname, void *usrdata);
extern int win_pop_tip_keypress(const char* widgetname, void *usrdata);
extern int prog_bar_service(const char* widgetname, void *usrdata);
extern int prog_bar_create(const char* widgetname, void *usrdata);
extern int prog_bar_destroy(const char* widgetname, void *usrdata);
extern int prog_bar_keypress(const char* widgetname, void *usrdata);
extern int win_prog_info_create(const char* widgetname, void *usrdata);
extern int win_prog_info_destroy(const char* widgetname, void *usrdata);
extern int win_prog_info_keypress(const char* widgetname, void *usrdata);
extern int win_prog_manage_create(const char* widgetname, void *usrdata);
extern int win_prog_manage_destroy(const char* widgetname, void *usrdata);
extern int win_prog_manage_keypress(const char* widgetname, void *usrdata);
extern int win_prog_manage_listview_keypress(const char* widgetname, void *usrdata);
extern int win_prog_manage_listview_get_total(const char* widgetname, void *usrdata);
extern int win_prog_manage_listview_get_data(const char* widgetname, void *usrdata);
extern int win_prog_manage_listview_change(const char* widgetname, void *usrdata);
extern int app_prog_menu_create(const char* widgetname, void *usrdata);
extern int app_prog_menu_keypress(const char* widgetname, void *usrdata);
extern int app_prog_menu_destroy(const char* widgetname, void *usrdata);
extern int app_prog_menu_box_keypress(const char* widgetname, void *usrdata);
extern int prog_num_service(const char* widgetname, void *usrdata);
extern int prog_num_create(const char* widgetname, void *usrdata);
extern int prog_num_destroy(const char* widgetname, void *usrdata);
extern int prog_num_keypress(const char* widgetname, void *usrdata);
extern int app_search_menu_create(const char* widgetname, void *usrdata);
extern int app_search_menu_keypress(const char* widgetname, void *usrdata);
extern int app_search_menu_destroy(const char* widgetname, void *usrdata);
extern int app_search_menu_box_keypress(const char* widgetname, void *usrdata);
extern int win_search_result_create(const char* widgetname, void *usrdata);
extern int win_search_result_destroy(const char* widgetname, void *usrdata);
extern int win_search_result_keypress(const char* widgetname, void *usrdata);
extern int app_search_result_service(const char* widgetname, void *usrdata);
extern int win_stb_info_create(const char* widgetname, void *usrdata);
extern int win_stb_info_destroy(const char* widgetname, void *usrdata);
extern int win_stb_info_keypress(const char* widgetname, void *usrdata);
extern int sys_set_service(const char* widgetname, void *usrdata);
extern int sys_set_create(const char* widgetname, void *usrdata);
extern int sys_set_destroy(const char* widgetname, void *usrdata);
extern int sys_set_keypress(const char* widgetname, void *usrdata);
extern int sys_set_listview1_get_count(const char* widgetname, void *usrdata);
extern int sys_set_listview1_get_data(const char* widgetname, void *usrdata);
extern int sys_set_listview1_change(const char* widgetname, void *usrdata);
extern int sys_set_listview1_keypress(const char* widgetname, void *usrdata);
extern int sys_set_listview2_get_count(const char* widgetname, void *usrdata);
extern int sys_set_listview2_get_data(const char* widgetname, void *usrdata);
extern int sys_set_listview2_change(const char* widgetname, void *usrdata);
extern int sys_set_listview2_keypress(const char* widgetname, void *usrdata);
extern int app_system_menu_box_keypress(const char* widgetname, void *usrdata);
extern int app_system_menu_box1_keypress(const char* widgetname, void *usrdata);
extern int win_sys_update_create(const char* widgetname, void *usrdata);
extern int win_sys_update_destroy(const char* widgetname, void *usrdata);
extern int win_sys_update_keypress(const char* widgetname, void *usrdata);
extern int win_trans_set_service(const char* widgetname, void *usrdata);
extern int win_trans_set_create(const char* widgetname, void *usrdata);
extern int win_trans_set_destroy(const char* widgetname, void *usrdata);
extern int win_trans_set_keypress(const char* widgetname, void *usrdata);
extern int win_videocolor_set_service(const char* widgetname, void *usrdata);
extern int win_videocolor_set_create(const char* widgetname, void *usrdata);
extern int win_videocolor_set_destroy(const char* widgetname, void *usrdata);
extern int win_videocolor_set_keypress(const char* widgetname, void *usrdata);
extern int app_video_menu_create(const char* widgetname, void *usrdata);
extern int app_video_menu_keypress(const char* widgetname, void *usrdata);
extern int app_video_menu_destroy(const char* widgetname, void *usrdata);
extern int app_video_menu_box_keypress(const char* widgetname, void *usrdata);
extern int win_video_set_service(const char* widgetname, void *usrdata);
extern int win_video_set_create(const char* widgetname, void *usrdata);
extern int win_video_set_destroy(const char* widgetname, void *usrdata);
extern int win_video_set_keypress(const char* widgetname, void *usrdata);
extern int win_volume_service(const char* widgetname, void *usrdata);
extern int win_volume_create(const char* widgetname, void *usrdata);
extern int win_volume_destroy(const char* widgetname, void *usrdata);
extern int win_volume_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_baseinfo_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_baseinfo_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_baseinfo_keypress(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_create(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_destroy(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_listview_key_press(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_keypress(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_get_count(const char* widgetname, void *usrdata);
extern int app_dvb_cas_email_get_data(const char* widgetname, void *usrdata);
extern int win_dvb_cas_email_content_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_email_content_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_email_content_keypress(const char* widgetname, void *usrdata);
extern int app_operatorinfo_create(const char* widgetname, void *usrdata);
extern int app_operatorinfo_destroy(const char* widgetname, void *usrdata);
extern int app_operatorinfo_keypress(const char* widgetname, void *usrdata);
extern int app_operatorinfo_list_get_total(const char* widgetname, void *usrdata);
extern int app_operatorinfo_list_get_data(const char* widgetname, void *usrdata);
extern int app_operatorinfo_list_change(const char* widgetname, void *usrdata);
extern int app_entitle_create(const char* widgetname, void *usrdata);
extern int app_entitle_destroy(const char* widgetname, void *usrdata);
extern int app_entitle_keypress(const char* widgetname, void *usrdata);
extern int app_entitle_list_get_total(const char* widgetname, void *usrdata);
extern int app_entitle_list_get_data(const char* widgetname, void *usrdata);
extern int app_entitle_list_change(const char* widgetname, void *usrdata);
extern int win_dvb_cas_pin_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_pin_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_pin_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_pin_box_keypress(const char* widgetname, void *usrdata);
extern int win_popmsg_create(const char* widgetname, void *usrdata);
extern int win_popmsg_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_rating_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_rating_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_rating_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_stb_pair_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_stb_pair_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_stb_pair_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_stb_pair_box_keypress(const char* widgetname, void *usrdata);
extern int win_dvb_cas_worktime_create(const char* widgetname, void *usrdata);
extern int win_dvb_cas_worktime_destroy(const char* widgetname, void *usrdata);
extern int win_dvb_cas_worktime_keypress(const char* widgetname, void *usrdata);
 
extern int disk_information_create(const char* widgetname, void *usrdata);
extern int disk_information_destroy(const char* widgetname, void *usrdata);
extern int disk_information_keypress(const char* widgetname, void *usrdata);
extern int disk_information_listview_get_total(const char* widgetname, void *usrdata);
extern int disk_information_listview_get_data(const char* widgetname, void *usrdata);
extern int disk_information_listview_draw(const char* widgetname, void *usrdata);
extern int app_pvr_bar_create(const char* widgetname, void *usrdata);
extern int app_pvr_bar_destroy(const char* widgetname, void *usrdata);
extern int app_pvr_bar_got_focus(const char* widgetname, void *usrdata);
extern int app_pvr_bar_lost_focus(const char* widgetname, void *usrdata);
extern int app_duration_set_keypress(const char* widgetname, void *usrdata);
extern int app_duration_set_create(const char* widgetname, void *usrdata);
extern int app_duration_set_destroy(const char* widgetname, void *usrdata);
extern int app_pvr_bar_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_seek_slider_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_media_create(const char* widgetname, void *usrdata);
extern int app_pvr_media_destroy(const char* widgetname, void *usrdata);
extern int app_pvr_media_keypress(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_get_total(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_get_data(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_draw(const char* widgetname, void *usrdata);
extern int app_pvr_media_list_change(const char* widgetname, void *usrdata);
extern int pvr_management_create(const char* widgetname, void *usrdata);
extern int pvr_management_destroy(const char* widgetname, void *usrdata);
extern int pvr_management_keypress(const char* widgetname, void *usrdata);
extern int pvr_management_box_keypress(const char* widgetname, void *usrdata);
extern int down_view_listview_init(const char* widgetname, void *usrdata);
extern int down_view_listview_get_count(const char* widgetname, void *usrdata);
extern int down_view_listview_get_data(const char* widgetname, void *usrdata);
extern int down_view_listview_change(const char* widgetname, void *usrdata);
extern int down_view_listview_keypress(const char* widgetname, void *usrdata);
extern int file_browser_service(const char* widgetname, void *usrdata);
extern int file_browser_init(const char* widgetname, void *usrdata);
extern int file_browser_destroy(const char* widgetname, void *usrdata);
extern int file_browser_keypress(const char* widgetname, void *usrdata);
extern int file_browser_listview_get_count(const char* widgetname, void *usrdata);
extern int file_browser_listview_get_data(const char* widgetname, void *usrdata);
extern int file_browser_listview_change(const char* widgetname, void *usrdata);
extern int file_browser_listview_keypress(const char* widgetname, void *usrdata);
extern int file_browser_lost_focus(const char* widgetname, void *usrdata);
extern int file_browser_got_focus(const char* widgetname, void *usrdata);
extern int file_edit_init(const char* widgetname, void *usrdata);
extern int file_edit_keypress(const char* widgetname, void *usrdata);
extern int media_centre_init(const char* widgetname, void *usrdata);
extern int media_centre_destroy(const char* widgetname, void *usrdata);
extern int media_centre_keypress(const char* widgetname, void *usrdata);
extern int media_centre_button_video_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_music_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_picture_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_text_clicked(const char* widgetname, void *usrdata);
extern int media_centre_button_file_clicked(const char* widgetname, void *usrdata);
extern int media_centre_item_change(const char* widgetname, void *usrdata);
extern int media_centre_box_keypress(const char* widgetname, void *usrdata);
extern int media_info_service(const char* widgetname, void *usrdata);
extern int media_info_init(const char* widgetname, void *usrdata);
extern int media_info_destroy(const char* widgetname, void *usrdata);
extern int media_info_keypress(const char* widgetname, void *usrdata);
extern int popmsg_init(const char* widgetname, void *usrdata);
extern int popmsg_keypress(const char* widgetname, void *usrdata);
extern int movie_info_service(const char* widgetname, void *usrdata);
extern int movie_info_init(const char* widgetname, void *usrdata);
extern int movie_info_destroy(const char* widgetname, void *usrdata);
extern int movie_info_keypress(const char* widgetname, void *usrdata);
extern int movie_set_service(const char* widgetname, void *usrdata);
extern int movie_set_init(const char* widgetname, void *usrdata);
extern int movie_set_destroy(const char* widgetname, void *usrdata);
extern int movie_set_keypress(const char* widgetname, void *usrdata);
extern int movie_subt_service(const char* widgetname, void *usrdata);
extern int movie_subt_init(const char* widgetname, void *usrdata);
extern int movie_subt_destroy(const char* widgetname, void *usrdata);
extern int movie_subt_keypress(const char* widgetname, void *usrdata);
extern int movie_view_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int movie_view_cursor_keypress(const char* widgetname, void *usrdata);
extern int movie_view_box_keypress(const char* widgetname, void *usrdata);
extern int movie_view_got_focus(const char* widgetname, void *usrdata);
extern int movie_view_lost_focus(const char* widgetname, void *usrdata);
extern int movie_view_service(const char* widgetname, void *usrdata);
extern int movie_view_init(const char* widgetname, void *usrdata);
extern int movie_view_destroy(const char* widgetname, void *usrdata);
extern int movie_media_view_keypress(const char* widgetname, void *usrdata);
extern int movie_media_service(const char* widgetname, void *usrdata);
extern int movie_view_keypress(const char* widgetname, void *usrdata);
extern int music_set_service(const char* widgetname, void *usrdata);
extern int music_set_init(const char* widgetname, void *usrdata);
extern int music_set_destroy(const char* widgetname, void *usrdata);
extern int music_set_keypress(const char* widgetname, void *usrdata);
extern int music_view_sliderbar_keypress(const char* widgetname, void *usrdata);
extern int music_view_cursor_keypress(const char* widgetname, void *usrdata);
extern int music_view_box_keypress(const char* widgetname, void *usrdata);
extern int music_view_got_focus(const char* widgetname, void *usrdata);
extern int music_view_lost_focus(const char* widgetname, void *usrdata);
extern int music_view_canvas_init(const char* widgetname, void *usrdata);
extern int music_view_service(const char* widgetname, void *usrdata);
extern int music_view_init(const char* widgetname, void *usrdata);
extern int music_view_destroy(const char* widgetname, void *usrdata);
extern int music_view_keypress(const char* widgetname, void *usrdata);
extern int open_file_service(const char* widgetname, void *usrdata);
extern int open_file_init(const char* widgetname, void *usrdata);
extern int open_file_keypress(const char* widgetname, void *usrdata);
extern int open_file_listview_get_count(const char* widgetname, void *usrdata);
extern int open_file_listview_get_data(const char* widgetname, void *usrdata);
extern int open_file_listview_keypress(const char* widgetname, void *usrdata);
extern int pic_info_service(const char* widgetname, void *usrdata);
extern int pic_info_init(const char* widgetname, void *usrdata);
extern int pic_info_keypress(const char* widgetname, void *usrdata);
extern int pic_set_service(const char* widgetname, void *usrdata);
extern int pic_set_init(const char* widgetname, void *usrdata);
extern int pic_set_destroy(const char* widgetname, void *usrdata);
extern int pic_set_keypress(const char* widgetname, void *usrdata);
extern int pic_view_box_keypress(const char* widgetname, void *usrdata);
extern int pic_view_service(const char* widgetname, void *usrdata);
extern int pic_view_init(const char* widgetname, void *usrdata);
extern int pic_view_destroy(const char* widgetname, void *usrdata);
extern int pic_view_keypress(const char* widgetname, void *usrdata);
extern int pic_view_got_focus(const char* widgetname, void *usrdata);
extern int pic_view_lost_focus(const char* widgetname, void *usrdata);
extern int pmp_set_init(const char* widgetname, void *usrdata);
extern int pmp_set_destroy(const char* widgetname, void *usrdata);
extern int pmp_set_keypress(const char* widgetname, void *usrdata);
extern int text_set_service(const char* widgetname, void *usrdata);
extern int text_set_init(const char* widgetname, void *usrdata);
extern int text_set_destroy(const char* widgetname, void *usrdata);
extern int text_set_keypress(const char* widgetname, void *usrdata);
extern int text_view_service(const char* widgetname, void *usrdata);
extern int text_view_init(const char* widgetname, void *usrdata);
extern int text_view_destroy(const char* widgetname, void *usrdata);
extern int text_view_keypress(const char* widgetname, void *usrdata);
extern int text_view_got_focus(const char* widgetname, void *usrdata);
extern int text_view_lost_focus(const char* widgetname, void *usrdata);
extern int volume_service(const char* widgetname, void *usrdata);
extern int volume_init(const char* widgetname, void *usrdata);
extern int volume_destroy(const char* widgetname, void *usrdata);
extern int volume_keypress(const char* widgetname, void *usrdata);
 
 
status_t signal_connect_handler(void)
{
	status_t ret = GXCORE_SUCCESS;
	ret |= SIGNAL_CONNECT(app_file_list_create);
	ret |= SIGNAL_CONNECT(app_file_list_destroy);
	ret |= SIGNAL_CONNECT(app_file_list_get_total);
	ret |= SIGNAL_CONNECT(app_file_list_keypress);
	ret |= SIGNAL_CONNECT(app_file_list_get_data);
	ret |= SIGNAL_CONNECT(app_file_list_draw);
	ret |= SIGNAL_CONNECT(app_file_list_change);
	ret |= SIGNAL_CONNECT(app_popmsg_init);
	ret |= SIGNAL_CONNECT(app_popmsg_keypress);
	ret |= SIGNAL_CONNECT(top);
	ret |= SIGNAL_CONNECT(app_update_menu_create);
	ret |= SIGNAL_CONNECT(app_update_menu_destroy);
	ret |= SIGNAL_CONNECT(app_update_menu_keypress);
	ret |= SIGNAL_CONNECT(app_update_menu_box_keypress);
	ret |= SIGNAL_CONNECT(app_update_manual_create);
	ret |= SIGNAL_CONNECT(app_update_manual_destroy);
	ret |= SIGNAL_CONNECT(app_update_manual_keypress);
	ret |= SIGNAL_CONNECT(app_update_manual_box_keypress);
	ret |= SIGNAL_CONNECT(app_update_manual_service);
	ret |= SIGNAL_CONNECT(app_advanced_menu_create);
	ret |= SIGNAL_CONNECT(app_advanced_menu_keypress);
	ret |= SIGNAL_CONNECT(app_advanced_menu_destroy);
	ret |= SIGNAL_CONNECT(app_advanced_menu_box_keypress);
	ret |= SIGNAL_CONNECT(win_all_search_create);
	ret |= SIGNAL_CONNECT(win_all_search_destroy);
	ret |= SIGNAL_CONNECT(win_all_search_keypress);
	ret |= SIGNAL_CONNECT(win_audio_set_service);
	ret |= SIGNAL_CONNECT(win_audio_set_create);
	ret |= SIGNAL_CONNECT(win_audio_set_destroy);
	ret |= SIGNAL_CONNECT(win_audio_set_keypress);
	ret |= SIGNAL_CONNECT(book_manage_service);
	ret |= SIGNAL_CONNECT(book_manage_create);
	ret |= SIGNAL_CONNECT(book_manage_destroy);
	ret |= SIGNAL_CONNECT(book_manage_keypress);
	ret |= SIGNAL_CONNECT(book_manage_listview_get_count);
	ret |= SIGNAL_CONNECT(book_manage_listview_get_data);
	ret |= SIGNAL_CONNECT(book_manage_listview_change);
	ret |= SIGNAL_CONNECT(book_manage_listview_draw);
	ret |= SIGNAL_CONNECT(book_manage_listview_keypress);
	ret |= SIGNAL_CONNECT(app_ca_info_menu_create);
	ret |= SIGNAL_CONNECT(app_ca_info_menu_keypress);
	ret |= SIGNAL_CONNECT(win_channel_set_create);
	ret |= SIGNAL_CONNECT(win_channel_set_destroy);
	ret |= SIGNAL_CONNECT(win_channel_set_keypress);
	ret |= SIGNAL_CONNECT(win_favorite_prog_list_create);
	ret |= SIGNAL_CONNECT(win_favorite_prog_list_destroy);
	ret |= SIGNAL_CONNECT(win_favorite_prog_list_keypress);
	ret |= SIGNAL_CONNECT(win_favorite_prog_listview_get_total);
	ret |= SIGNAL_CONNECT(win_favorite_prog_listview_get_data);
	ret |= SIGNAL_CONNECT(win_favorite_prog_listview_change);
	ret |= SIGNAL_CONNECT(win_favorite_prog_list_show);
	ret |= SIGNAL_CONNECT(app_full_screen_create);
	ret |= SIGNAL_CONNECT(full_screen_service);
	ret |= SIGNAL_CONNECT(app_full_screen_destroy);
	ret |= SIGNAL_CONNECT(app_full_screen_keypress);
	ret |= SIGNAL_CONNECT(win_lang_set_service);
	ret |= SIGNAL_CONNECT(win_lang_set_create);
	ret |= SIGNAL_CONNECT(win_lang_set_destroy);
	ret |= SIGNAL_CONNECT(win_lang_set_keypress);
	ret |= SIGNAL_CONNECT(win_main_frequency_set_create);
	ret |= SIGNAL_CONNECT(win_main_frequency_set_destroy);
	ret |= SIGNAL_CONNECT(win_main_frequency_set_keypress);
	ret |= SIGNAL_CONNECT(win_main_menu_create);
	ret |= SIGNAL_CONNECT(win_main_menu_destroy);
	ret |= SIGNAL_CONNECT(win_main_menu_keypress);
	ret |= SIGNAL_CONNECT(win_main_menu_show);
	ret |= SIGNAL_CONNECT(app_main_menu_boxr_keypress);
	ret |= SIGNAL_CONNECT(app_main_menu_box_keypress);
	ret |= SIGNAL_CONNECT(win_manual_search_create);
	ret |= SIGNAL_CONNECT(win_manual_search_destroy);
	ret |= SIGNAL_CONNECT(win_manual_search_keypress);
	ret |= SIGNAL_CONNECT(win_epg_list_create);
	ret |= SIGNAL_CONNECT(win_epg_list_lost_focus);
	ret |= SIGNAL_CONNECT(win_epg_list_destroy);
	ret |= SIGNAL_CONNECT(win_epg_list_show);
	ret |= SIGNAL_CONNECT(win_epg_list_keypress);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_get_total);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_get_data);
	ret |= SIGNAL_CONNECT(app_epg_prog_list_change);
	ret |= SIGNAL_CONNECT(app_epg_schedule_listview_change);
	ret |= SIGNAL_CONNECT(app_epg_schedule_listview_get_total);
	ret |= SIGNAL_CONNECT(app_epg_schedule_listview_get_data);
	ret |= SIGNAL_CONNECT(win_menu_tv_list_create);
	ret |= SIGNAL_CONNECT(win_menu_tv_list_destroy);
	ret |= SIGNAL_CONNECT(win_menu_tv_list_keypress);
	ret |= SIGNAL_CONNECT(win_tv_prog_listview_get_total);
	ret |= SIGNAL_CONNECT(win_tv_prog_listview_get_data);
	ret |= SIGNAL_CONNECT(win_tv_prog_listview_change);
	ret |= SIGNAL_CONNECT(win_passwd_set_service);
	ret |= SIGNAL_CONNECT(win_passwd_set_create);
	ret |= SIGNAL_CONNECT(win_passwd_set_destroy);
	ret |= SIGNAL_CONNECT(win_passwd_set_box_keypress);
	ret |= SIGNAL_CONNECT(win_passwd_set_keypress);
	ret |= SIGNAL_CONNECT(win_password_check_create);
	ret |= SIGNAL_CONNECT(win_password_check_destroy);
	ret |= SIGNAL_CONNECT(win_password_check_edit_keypress);
	ret |= SIGNAL_CONNECT(win_password_check_reach_end);
	ret |= SIGNAL_CONNECT(win_password_check_keypress);
	ret |= SIGNAL_CONNECT(win_password_input_create);
	ret |= SIGNAL_CONNECT(win_password_input_destroy);
	ret |= SIGNAL_CONNECT(win_password_input_edit_keypress);
	ret |= SIGNAL_CONNECT(win_password_input_reach_end);
	ret |= SIGNAL_CONNECT(win_password_input_keypress);
	ret |= SIGNAL_CONNECT(win_pop_tip_create);
	ret |= SIGNAL_CONNECT(win_pop_tip_destroy);
	ret |= SIGNAL_CONNECT(win_pop_tip_keypress);
	ret |= SIGNAL_CONNECT(prog_bar_service);
	ret |= SIGNAL_CONNECT(prog_bar_create);
	ret |= SIGNAL_CONNECT(prog_bar_destroy);
	ret |= SIGNAL_CONNECT(prog_bar_keypress);
	ret |= SIGNAL_CONNECT(win_prog_info_create);
	ret |= SIGNAL_CONNECT(win_prog_info_destroy);
	ret |= SIGNAL_CONNECT(win_prog_info_keypress);
	ret |= SIGNAL_CONNECT(win_prog_manage_create);
	ret |= SIGNAL_CONNECT(win_prog_manage_destroy);
	ret |= SIGNAL_CONNECT(win_prog_manage_keypress);
	ret |= SIGNAL_CONNECT(win_prog_manage_listview_keypress);
	ret |= SIGNAL_CONNECT(win_prog_manage_listview_get_total);
	ret |= SIGNAL_CONNECT(win_prog_manage_listview_get_data);
	ret |= SIGNAL_CONNECT(win_prog_manage_listview_change);
	ret |= SIGNAL_CONNECT(app_prog_menu_create);
	ret |= SIGNAL_CONNECT(app_prog_menu_keypress);
	ret |= SIGNAL_CONNECT(app_prog_menu_destroy);
	ret |= SIGNAL_CONNECT(app_prog_menu_box_keypress);
	ret |= SIGNAL_CONNECT(prog_num_service);
	ret |= SIGNAL_CONNECT(prog_num_create);
	ret |= SIGNAL_CONNECT(prog_num_destroy);
	ret |= SIGNAL_CONNECT(prog_num_keypress);
	ret |= SIGNAL_CONNECT(app_search_menu_create);
	ret |= SIGNAL_CONNECT(app_search_menu_keypress);
	ret |= SIGNAL_CONNECT(app_search_menu_destroy);
	ret |= SIGNAL_CONNECT(app_search_menu_box_keypress);
	ret |= SIGNAL_CONNECT(win_search_result_create);
	ret |= SIGNAL_CONNECT(win_search_result_destroy);
	ret |= SIGNAL_CONNECT(win_search_result_keypress);
	ret |= SIGNAL_CONNECT(app_search_result_service);
	ret |= SIGNAL_CONNECT(win_stb_info_create);
	ret |= SIGNAL_CONNECT(win_stb_info_destroy);
	ret |= SIGNAL_CONNECT(win_stb_info_keypress);
	ret |= SIGNAL_CONNECT(sys_set_service);
	ret |= SIGNAL_CONNECT(sys_set_create);
	ret |= SIGNAL_CONNECT(sys_set_destroy);
	ret |= SIGNAL_CONNECT(sys_set_keypress);
	ret |= SIGNAL_CONNECT(sys_set_listview1_get_count);
	ret |= SIGNAL_CONNECT(sys_set_listview1_get_data);
	ret |= SIGNAL_CONNECT(sys_set_listview1_change);
	ret |= SIGNAL_CONNECT(sys_set_listview1_keypress);
	ret |= SIGNAL_CONNECT(sys_set_listview2_get_count);
	ret |= SIGNAL_CONNECT(sys_set_listview2_get_data);
	ret |= SIGNAL_CONNECT(sys_set_listview2_change);
	ret |= SIGNAL_CONNECT(sys_set_listview2_keypress);
	ret |= SIGNAL_CONNECT(app_system_menu_box_keypress);
	ret |= SIGNAL_CONNECT(app_system_menu_box1_keypress);
	ret |= SIGNAL_CONNECT(win_sys_update_create);
	ret |= SIGNAL_CONNECT(win_sys_update_destroy);
	ret |= SIGNAL_CONNECT(win_sys_update_keypress);
	ret |= SIGNAL_CONNECT(win_trans_set_service);
	ret |= SIGNAL_CONNECT(win_trans_set_create);
	ret |= SIGNAL_CONNECT(win_trans_set_destroy);
	ret |= SIGNAL_CONNECT(win_trans_set_keypress);
	ret |= SIGNAL_CONNECT(win_videocolor_set_service);
	ret |= SIGNAL_CONNECT(win_videocolor_set_create);
	ret |= SIGNAL_CONNECT(win_videocolor_set_destroy);
	ret |= SIGNAL_CONNECT(win_videocolor_set_keypress);
	ret |= SIGNAL_CONNECT(app_video_menu_create);
	ret |= SIGNAL_CONNECT(app_video_menu_keypress);
	ret |= SIGNAL_CONNECT(app_video_menu_destroy);
	ret |= SIGNAL_CONNECT(app_video_menu_box_keypress);
	ret |= SIGNAL_CONNECT(win_video_set_service);
	ret |= SIGNAL_CONNECT(win_video_set_create);
	ret |= SIGNAL_CONNECT(win_video_set_destroy);
	ret |= SIGNAL_CONNECT(win_video_set_keypress);
	ret |= SIGNAL_CONNECT(win_volume_service);
	ret |= SIGNAL_CONNECT(win_volume_create);
	ret |= SIGNAL_CONNECT(win_volume_destroy);
	ret |= SIGNAL_CONNECT(win_volume_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_baseinfo_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_baseinfo_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_baseinfo_keypress);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_create);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_destroy);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_listview_key_press);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_keypress);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_get_count);
	ret |= SIGNAL_CONNECT(app_dvb_cas_email_get_data);
	ret |= SIGNAL_CONNECT(win_dvb_cas_email_content_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_email_content_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_email_content_keypress);
	ret |= SIGNAL_CONNECT(app_operatorinfo_create);
	ret |= SIGNAL_CONNECT(app_operatorinfo_destroy);
	ret |= SIGNAL_CONNECT(app_operatorinfo_keypress);
	ret |= SIGNAL_CONNECT(app_operatorinfo_list_get_total);
	ret |= SIGNAL_CONNECT(app_operatorinfo_list_get_data);
	ret |= SIGNAL_CONNECT(app_operatorinfo_list_change);
	ret |= SIGNAL_CONNECT(app_entitle_create);
	ret |= SIGNAL_CONNECT(app_entitle_destroy);
	ret |= SIGNAL_CONNECT(app_entitle_keypress);
	ret |= SIGNAL_CONNECT(app_entitle_list_get_total);
	ret |= SIGNAL_CONNECT(app_entitle_list_get_data);
	ret |= SIGNAL_CONNECT(app_entitle_list_change);
	ret |= SIGNAL_CONNECT(win_dvb_cas_pin_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_pin_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_pin_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_pin_box_keypress);
	ret |= SIGNAL_CONNECT(win_popmsg_create);
	ret |= SIGNAL_CONNECT(win_popmsg_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_rating_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_rating_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_rating_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_stb_pair_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_stb_pair_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_stb_pair_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_stb_pair_box_keypress);
	ret |= SIGNAL_CONNECT(win_dvb_cas_worktime_create);
	ret |= SIGNAL_CONNECT(win_dvb_cas_worktime_destroy);
	ret |= SIGNAL_CONNECT(win_dvb_cas_worktime_keypress);
 
	ret |= SIGNAL_CONNECT(disk_information_create);
	ret |= SIGNAL_CONNECT(disk_information_destroy);
	ret |= SIGNAL_CONNECT(disk_information_keypress);
	ret |= SIGNAL_CONNECT(disk_information_listview_get_total);
	ret |= SIGNAL_CONNECT(disk_information_listview_get_data);
	ret |= SIGNAL_CONNECT(disk_information_listview_draw);
	ret |= SIGNAL_CONNECT(app_pvr_bar_create);
	ret |= SIGNAL_CONNECT(app_pvr_bar_destroy);
	ret |= SIGNAL_CONNECT(app_pvr_bar_got_focus);
	ret |= SIGNAL_CONNECT(app_pvr_bar_lost_focus);
	ret |= SIGNAL_CONNECT(app_duration_set_keypress);
	ret |= SIGNAL_CONNECT(app_duration_set_create);
	ret |= SIGNAL_CONNECT(app_duration_set_destroy);
	ret |= SIGNAL_CONNECT(app_pvr_bar_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_seek_slider_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_media_create);
	ret |= SIGNAL_CONNECT(app_pvr_media_destroy);
	ret |= SIGNAL_CONNECT(app_pvr_media_keypress);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_get_total);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_get_data);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_draw);
	ret |= SIGNAL_CONNECT(app_pvr_media_list_change);
	ret |= SIGNAL_CONNECT(pvr_management_create);
	ret |= SIGNAL_CONNECT(pvr_management_destroy);
	ret |= SIGNAL_CONNECT(pvr_management_keypress);
	ret |= SIGNAL_CONNECT(pvr_management_box_keypress);
	ret |= SIGNAL_CONNECT(down_view_listview_init);
	ret |= SIGNAL_CONNECT(down_view_listview_get_count);
	ret |= SIGNAL_CONNECT(down_view_listview_get_data);
	ret |= SIGNAL_CONNECT(down_view_listview_change);
	ret |= SIGNAL_CONNECT(down_view_listview_keypress);
	ret |= SIGNAL_CONNECT(file_browser_service);
	ret |= SIGNAL_CONNECT(file_browser_init);
	ret |= SIGNAL_CONNECT(file_browser_destroy);
	ret |= SIGNAL_CONNECT(file_browser_keypress);
	ret |= SIGNAL_CONNECT(file_browser_listview_get_count);
	ret |= SIGNAL_CONNECT(file_browser_listview_get_data);
	ret |= SIGNAL_CONNECT(file_browser_listview_change);
	ret |= SIGNAL_CONNECT(file_browser_listview_keypress);
	ret |= SIGNAL_CONNECT(file_browser_lost_focus);
	ret |= SIGNAL_CONNECT(file_browser_got_focus);
	ret |= SIGNAL_CONNECT(file_edit_init);
	ret |= SIGNAL_CONNECT(file_edit_keypress);
	ret |= SIGNAL_CONNECT(media_centre_init);
	ret |= SIGNAL_CONNECT(media_centre_destroy);
	ret |= SIGNAL_CONNECT(media_centre_keypress);
	ret |= SIGNAL_CONNECT(media_centre_button_video_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_music_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_picture_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_text_clicked);
	ret |= SIGNAL_CONNECT(media_centre_button_file_clicked);
	ret |= SIGNAL_CONNECT(media_centre_item_change);
	ret |= SIGNAL_CONNECT(media_centre_box_keypress);
	ret |= SIGNAL_CONNECT(media_info_service);
	ret |= SIGNAL_CONNECT(media_info_init);
	ret |= SIGNAL_CONNECT(media_info_destroy);
	ret |= SIGNAL_CONNECT(media_info_keypress);
	ret |= SIGNAL_CONNECT(popmsg_init);
	ret |= SIGNAL_CONNECT(popmsg_keypress);
	ret |= SIGNAL_CONNECT(movie_info_service);
	ret |= SIGNAL_CONNECT(movie_info_init);
	ret |= SIGNAL_CONNECT(movie_info_destroy);
	ret |= SIGNAL_CONNECT(movie_info_keypress);
	ret |= SIGNAL_CONNECT(movie_set_service);
	ret |= SIGNAL_CONNECT(movie_set_init);
	ret |= SIGNAL_CONNECT(movie_set_destroy);
	ret |= SIGNAL_CONNECT(movie_set_keypress);
	ret |= SIGNAL_CONNECT(movie_subt_service);
	ret |= SIGNAL_CONNECT(movie_subt_init);
	ret |= SIGNAL_CONNECT(movie_subt_destroy);
	ret |= SIGNAL_CONNECT(movie_subt_keypress);
	ret |= SIGNAL_CONNECT(movie_view_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(movie_view_cursor_keypress);
	ret |= SIGNAL_CONNECT(movie_view_box_keypress);
	ret |= SIGNAL_CONNECT(movie_view_got_focus);
	ret |= SIGNAL_CONNECT(movie_view_lost_focus);
	ret |= SIGNAL_CONNECT(movie_view_service);
	ret |= SIGNAL_CONNECT(movie_view_init);
	ret |= SIGNAL_CONNECT(movie_view_destroy);
	ret |= SIGNAL_CONNECT(movie_media_view_keypress);
	ret |= SIGNAL_CONNECT(movie_media_service);
	ret |= SIGNAL_CONNECT(movie_view_keypress);
	ret |= SIGNAL_CONNECT(music_set_service);
	ret |= SIGNAL_CONNECT(music_set_init);
	ret |= SIGNAL_CONNECT(music_set_destroy);
	ret |= SIGNAL_CONNECT(music_set_keypress);
	ret |= SIGNAL_CONNECT(music_view_sliderbar_keypress);
	ret |= SIGNAL_CONNECT(music_view_cursor_keypress);
	ret |= SIGNAL_CONNECT(music_view_box_keypress);
	ret |= SIGNAL_CONNECT(music_view_got_focus);
	ret |= SIGNAL_CONNECT(music_view_lost_focus);
	ret |= SIGNAL_CONNECT(music_view_canvas_init);
	ret |= SIGNAL_CONNECT(music_view_service);
	ret |= SIGNAL_CONNECT(music_view_init);
	ret |= SIGNAL_CONNECT(music_view_destroy);
	ret |= SIGNAL_CONNECT(music_view_keypress);
	ret |= SIGNAL_CONNECT(open_file_service);
	ret |= SIGNAL_CONNECT(open_file_init);
	ret |= SIGNAL_CONNECT(open_file_keypress);
	ret |= SIGNAL_CONNECT(open_file_listview_get_count);
	ret |= SIGNAL_CONNECT(open_file_listview_get_data);
	ret |= SIGNAL_CONNECT(open_file_listview_keypress);
	ret |= SIGNAL_CONNECT(pic_info_service);
	ret |= SIGNAL_CONNECT(pic_info_init);
	ret |= SIGNAL_CONNECT(pic_info_keypress);
	ret |= SIGNAL_CONNECT(pic_set_service);
	ret |= SIGNAL_CONNECT(pic_set_init);
	ret |= SIGNAL_CONNECT(pic_set_destroy);
	ret |= SIGNAL_CONNECT(pic_set_keypress);
	ret |= SIGNAL_CONNECT(pic_view_box_keypress);
	ret |= SIGNAL_CONNECT(pic_view_service);
	ret |= SIGNAL_CONNECT(pic_view_init);
	ret |= SIGNAL_CONNECT(pic_view_destroy);
	ret |= SIGNAL_CONNECT(pic_view_keypress);
	ret |= SIGNAL_CONNECT(pic_view_got_focus);
	ret |= SIGNAL_CONNECT(pic_view_lost_focus);
	ret |= SIGNAL_CONNECT(pmp_set_init);
	ret |= SIGNAL_CONNECT(pmp_set_destroy);
	ret |= SIGNAL_CONNECT(pmp_set_keypress);
	ret |= SIGNAL_CONNECT(text_set_service);
	ret |= SIGNAL_CONNECT(text_set_init);
	ret |= SIGNAL_CONNECT(text_set_destroy);
	ret |= SIGNAL_CONNECT(text_set_keypress);
	ret |= SIGNAL_CONNECT(text_view_service);
	ret |= SIGNAL_CONNECT(text_view_init);
	ret |= SIGNAL_CONNECT(text_view_destroy);
	ret |= SIGNAL_CONNECT(text_view_keypress);
	ret |= SIGNAL_CONNECT(text_view_got_focus);
	ret |= SIGNAL_CONNECT(text_view_lost_focus);
	ret |= SIGNAL_CONNECT(volume_service);
	ret |= SIGNAL_CONNECT(volume_init);
	ret |= SIGNAL_CONNECT(volume_destroy);
	ret |= SIGNAL_CONNECT(volume_keypress);
 
	return ret;
}
