#ifndef _DVBCA_CARD_TASK_H_
#define _DVBCA_CARD_TASK_H_


typedef enum 
{
	ECM_TYPE_CTRL_INFO = 0x01,
	ECM_TYPE_CW_INFO = 0x02,
	ECM_TYPE_EERO_TYPE = 0x03,
	ECM_TYPE_DATE = 0x04,
}DVBCA_ECM_DATA_TYPE;

typedef enum
{
	CARD_AUTHORIZE, 
	CARD_SEND_ECM,
	CARD_SEND_EMM,
	CARD_SEND_EVENT,
	CARD_SEND_CMD,
	CARD_READ_CAVER,
	CARD_READ_STBBAND,
	CARD_READ_PROVIDER,
	CARD_READ_PROVIDERINFO,
	CARD_READ_AUTHORIZE,
	CARD_WRITE_STBPAIR,
	CARD_WRITE_RATING,
	CARD_READ_RATING,
	CARD_WRITE_PIN,
	CARD_CHECK_PIN,
	CARD_READ_AC_LIST,
	CARD_WRITE_WORKTIME,
	CARD_READ_WORKTIME,
	CARD_READ_EVENT_INFO,
	CARD_EXIT_MSG,
}CARD_MSG_TYPE;

typedef enum
{
	CARD_REMOVE,
	CARD_INSERT,
	CARD_AUTHORIZE_FAILED,
}CARD_STATUS;

DVBCA_UINT16  DVBCA_CardGetVer(void);
int DVBCA_CardTaskInit(DVBCA_UINT8 ucThreadPriority);
void DVBCA_CardWaitCard(void);
int DVBCA_CardGetReadValue(DVBCA_UINT8 **pucBuffer, DVBCA_UINT32 *puiLen);
int DVBCA_CardGetStatus(void);
int DVBCA_CardCheckInsert(void);
void DVBCA_CardRemove(void);
DVBCA_UINT16 DVBCA_CardGetCardVer(void);

void DVBCA_CardTaskUnInit(void);
#endif
