#!/bin/sh

case "$1" in
    start)
        if [ ! -c /dev/panel0 ]; then
            echo "Install panel driver..."
            modprobe panel
        fi
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

